- hosts: all

  handlers:
    - name: "restart nginx"
      service:
        name: nginx
        state: restarted
      become: yes

  tasks:
    - name: "Roda: sudo apt-get update"
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
  
  tasks:
    - name: "Roda: Refresh packages"
      become: true
      apt:
        name: '*'
        state: latest
 
    - name: "Instala pacotes"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - nginx
        - default-jre

